/*
 * Adds support for standard color names, including CSS colors.
 *  @author Tim Halverson
 */
package actr.task;

import java.awt.Color;

public enum NamedColor {
	
	//	Standard Java AWT colors
	BLACK(Color.BLACK, "black"),
	BLUE(Color.BLUE, "blue"),
	CYAN(Color.CYAN, "cyan"),
	DARK_GRAY(Color.DARK_GRAY, "dark_gray"),
	GRAY(Color.GRAY, "gray"),
	GREEN(Color.GREEN, "green"),
	LIGHT_GRAY(Color.LIGHT_GRAY, "light_gray"),
	MAGENTA(Color.MAGENTA, "magenta"),
	ORANGE(Color.ORANGE, "orange"),
	PINK(Color.PINK, "pink"),
	RED(Color.RED, "red"),
	WHITE(Color.WHITE, "white"),
	YELLOW(Color.YELLOW, "yellow"),

	//	CSS colors
	ALICE_BLUE(new Color(0xF0F8FF), "alice_blue"),
	ANTIQUE_WHITE(new Color(0xFAEBD7), "antique_white"),
	AQUA(new Color(0x00FFFF), "aqua"),
	AQUA_MARINE(new Color(0x7FFFD4), "aqua_marine"),
	AZURE(new Color(0xF0FFFF), "azure"),
	BEIGE(new Color(0xF5F5DC), "beige"),
	BISQUE(new Color(0xFFE4C4), "bisque"),
	BLANCHED_ALMOND(new Color(0xFFEBCD), "blanched_almond"),
	BLUE_VIOLET(new Color(0x8A2BE2), "blue_violet"),
	BROWN(new Color(0xA52A2A), "brown"),
	BURLEY_WOOD(new Color(0xDEB887), "burley_wood"),
	CADET_BLUE(new Color(0x5F9EA0), "cadet_blue"),
	CHARTREUSE(new Color(0x7FFF00), "chartreuse"),
	CHOCOLATE(new Color(0xD2691E), "chocolate"),
	CORAL(new Color(0xFF7F50), "coral"),
	CORNFLOWER_BLUE(new Color(0x6495ED), "cornflower_blue"),
	CORNSILK(new Color(0xFFF8DC), "cornsilk"),
	CRIMSON(new Color(0xDC143C), "crimson"),
	DARK_BLUE(new Color(0x00008B), "dark_blue"),
	DARK_CYAN(new Color(0x008B8B), "dark_cyan"),
	DARK_GOLDEN_Rod(new Color(0xB8860B), "dark_golden_rod"),
	DARK_GREEN(new Color(0x006400), "dark_green"),
	DARK_KHAKI(new Color(0xBDB76B), "dark_khaki"),
	DARK_MAGENTA(new Color(0x8B008B), "dark_magenta"),
	DARK_OLIVE_GREEN(new Color(0x556B2F), "dark_olive_green"),
	DARK_ORANGE(new Color(0xFF8C00), "dark_orange"),
	DARK_ORCHID(new Color(0x9932CC), "dark_orchid"),
	DARK_RED(new Color(0x8B0000), "dark_red"),
	DARK_SALMON(new Color(0xE9967A), "dark_salmon"),
	DARK_SEA_GREEN(new Color(0x8FBC8F), "dark_sea_green"),
	DARK_SLATE_BLUE(new Color(0x483D8B), "dark_slate_blue"),
	DARK_SLATE_GRAY(new Color(0x2F4F4F), "dark_slate_gray"),
	DARK_TURQUOISE(new Color(0x00CED1), "dark_turquoise"),
	DARK_VIOLET(new Color(0x9400D3), "dark_violet"),
	DEEP_PINK(new Color(0xFF1493), "deep_pink"),
	DEEP_SKY_BLUE(new Color(0x00BFFF), "deep_sky_blue"),
	DIM_GRAY(new Color(0x696969), "dim_gray"),
	DODGER_BLUE(new Color(0x1E90FF), "dodger_blue"),
	FIRE_BRICK(new Color(0xB22222), "fire_brick"),
	FLORAL_WHITE(new Color(0xFFFAF0), "floral_white"),
	FOREST_GREEN(new Color(0x228B22), "forest_green"),
	FUCHSIA(new Color(0xFF00FF), "fuchsia"),
	GAINSBORO(new Color(0xDCDCDC), "gainsboro"),
	GHOST_WHITE(new Color(0xF8F8FF), "ghost_white"),
	GOLD(new Color(0xFFD700), "gold"),
	GOLDEN_ROD(new Color(0xDAA520), "golden_rod"),
	GREEN_YELLOW(new Color(0xADFF2F), "green_yellow"),
	HONEY_DEW(new Color(0xF0FFF0), "honey_dew"),
	HOT_PINK(new Color(0xFF69B4), "hot_pink"),
	INDIAN_RED (new Color(0xCD5C5C), "indian_red "),
	INDIGO(new Color(0x4B0082), "indigo"),
	IVORY(new Color(0xFFFFF0), "ivory"),
	KHAKI(new Color(0xF0E68C), "khaki"),
	LAVENDER(new Color(0xE6E6FA), "lavender"),
	LAVENDER_BLUSH(new Color(0xFFF0F5), "lavender_blush"),
	LAWN_GREEN(new Color(0x7CFC00), "lawn_green"),
	LEMON_CHIFFON(new Color(0xFFFACD), "lemon_chiffon"),
	LIGHT_BLUE(new Color(0xADD8E6), "light_blue"),
	LIGHT_CORAL(new Color(0xF08080), "light_coral"),
	LIGHT_CYAN(new Color(0xE0FFFF), "light_cyan"),
	LIGHT_GOLDEN_RodYellow(new Color(0xFAFAD2), "light_golden_rodyellow"),
	LIGHT_GREEN(new Color(0x90EE90), "light_green"),
	LIGHT_PINK(new Color(0xFFB6C1), "light_pink"),
	LIGHT_SALMON(new Color(0xFFA07A), "light_salmon"),
	LIGHT_SEA_GREEN(new Color(0x20B2AA), "light_sea_green"),
	LIGHT_SKY_BLUE(new Color(0x87CEFA), "light_sky_blue"),
	LIGHT_SLATE_GRAY(new Color(0x778899), "light_slate_gray"),
	LIGHT_STEEL_BLUE(new Color(0xB0C4DE), "light_steel_blue"),
	LIGHT_YELLOW(new Color(0xFFFFE0), "light_yellow"),
	LIME(new Color(0x00FF00), "lime"),
	LIME_GREEN(new Color(0x32CD32), "lime_green"),
	LINEN(new Color(0xFAF0E6), "linen"),
	MAROON(new Color(0x800000), "maroon"),
	MEDIUM_AQUA_MARINE(new Color(0x66CDAA), "medium_aqua_marine"),
	MEDIUM_BLUE(new Color(0x0000CD), "medium_blue"),
	MEDIUM_ORCHID(new Color(0xBA55D3), "medium_orchid"),
	MEDIUM_PURPLE(new Color(0x9370DB), "medium_purple"),
	MEDIUM_SEA_GREEN(new Color(0x3CB371), "medium_sea_green"),
	MEDIUM_SLATE_BLUE(new Color(0x7B68EE), "medium_slate_blue"),
	MEDIUM_SPRING_GREEN(new Color(0x00FA9A), "medium_spring_green"),
	MEDIUM_TURQUOISE(new Color(0x48D1CC), "medium_turquoise"),
	MEDIUM_VIOLET_RED(new Color(0xC71585), "medium_violet_red"),
	MIDNIGHT_BLUE(new Color(0x191970), "midnight_blue"),
	MINT_CREAM(new Color(0xF5FFFA), "mint_cream"),
	MISTY_ROSE(new Color(0xFFE4E1), "misty_rose"),
	MOCCASIN(new Color(0xFFE4B5), "moccasin"),
	NAVAJO_WHITE(new Color(0xFFDEAD), "navajo_white"),
	NAVY(new Color(0x000080), "navy"),
	OLD_LACE(new Color(0xFDF5E6), "old_lace"),
	OLIVE(new Color(0x808000), "olive"),
	OLIVE_DRAB(new Color(0x6B8E23), "olive_drab"),
	ORANGE_RED(new Color(0xFF4500), "orange_red"),
	ORCHID(new Color(0xDA70D6), "orchid"),
	PALE_GOLDEN_ROD(new Color(0xEEE8AA), "pale_golden_rod"),
	PALE_GREEN(new Color(0x98FB98), "pale_green"),
	PALE_TURQUOISE(new Color(0xAFEEEE), "pale_turquoise"),
	PALE_VIOLET_RED(new Color(0xDB7093), "pale_violet_red"),
	PAPAYA_WHIP(new Color(0xFFEFD5), "papaya_whip"),
	PEACH_PUFF(new Color(0xFFDAB9), "peach_puff"),
	PERU(new Color(0xCD853F), "peru"),
	PLUM(new Color(0xDDA0DD), "plum"),
	POWDER_BLUE(new Color(0xB0E0E6), "powder_blue"),
	PURPLE(new Color(0x800080), "purple"),
	ROSY_BROWN(new Color(0xBC8F8F), "rosy_brown"),
	ROYAL_BLUE(new Color(0x4169E1), "royal_blue"),
	SADDLE_BROWN(new Color(0x8B4513), "saddle_brown"),
	SALMON(new Color(0xFA8072), "salmon"),
	SANDY_BROWN(new Color(0xF4A460), "sandy_brown"),
	SEA_GREEN(new Color(0x2E8B57), "sea_green"),
	SEA_SHELL(new Color(0xFFF5EE), "sea_shell"),
	SIENNA(new Color(0xA0522D), "sienna"),
	SILVER(new Color(0xC0C0C0), "silver"),
	SKY_BLUE(new Color(0x87CEEB), "sky_blue"),
	SLATE_BLUE(new Color(0x6A5ACD), "slate_blue"),
	SLATE_GRAY(new Color(0x708090), "slate_gray"),
	SNOW(new Color(0xFFFAFA), "snow"),
	SPRING_GREEN(new Color(0x00FF7F), "spring_green"),
	STEEL_BLUE(new Color(0x4682B4), "steel_blue"),
	TAN(new Color(0xD2B48C), "tan"),
	TEAL(new Color(0x008080), "teal"),
	THISTLE(new Color(0xD8BFD8), "thistle"),
	TOMATO(new Color(0xFF6347), "tomato"),
	TURQUOISE(new Color(0x40E0D0), "turquoise"),
	VIOLET(new Color(0xEE82EE), "violet"),
	WHEAT(new Color(0xF5DEB3), "wheat"),
	WHITE_SMOKE(new Color(0xF5F5F5), "white_smoke"),
	YELLOW_GREEN(new Color(0x9ACD32), "yellow_green");
	
    private final Color awtColor;
    private final String colorName;

    private NamedColor(Color awtColor, String colorName) {
        this.awtColor = awtColor;
        this.colorName = colorName;
    }

    public Color getAwtColor() {
        return awtColor;
    }
    
    public String getColorName() {
    	return this.colorName;
    }
}
